-- Atlas Spaces: small, self-contained HTML mini-apps generated by prompting
-- an AI, shareable in a chat and remixable by anyone who can see them.
--
-- html is the entire mini-app: inline <style>/<script>, no build step, no
-- separate assets — rendered client-side in a sandboxed iframe (sandbox=
-- "allow-scripts", deliberately no allow-same-origin/allow-popups/
-- allow-top-navigation). That iframe sandbox is the real security boundary;
-- generation only applies a soft prompt-level guardrail on top of it.
--
-- parent_space_id links a remix to the Space it was generated from (its HTML
-- was given to the model as context alongside the new instruction). NULL for
-- an original Space. ON DELETE SET NULL rather than CASCADE: a remix must
-- keep working even if its ancestor is ever removed — it already carries its
-- own complete, independent HTML.
CREATE TABLE spaces (
    id              UUID PRIMARY KEY,
    creator_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_space_id UUID REFERENCES spaces(id) ON DELETE SET NULL,
    html            TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX spaces_creator_idx ON spaces(creator_id);

-- A message that shares a Space uses scheme = 'space' with a small JSON
-- pointer body (`{"spaceId":"..."}`) — same shape as 'call-log', a
-- server-readable text scheme carrying structured metadata rather than
-- prose. See models.rs::is_text_scheme.
